version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=mysql://root:prisma@db:3306/t3-docker
      - DISCORD_CLIENT_ID=1039277078358540328
      - DISCORD_CLIENT_SECRET=FErimEaxx6QfwmbTx0PPrUme7qGWTNzY
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=changeme
  db:
    image: mysql
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: t3-docker
